### ISSUE TITLE
How to clean hmr in production?

### ISSUE THREAD

**Issue by hulufei** [fluxxu/elm-hot-loader#10]
Hi

Like react-hot-reload, we can use `if (NODE_ENV=production)` to clean hot reload code in production, how to do this in elm-hot-loader?

thanks

**Comment by fluxxu** [comment]
Sorry for late reply!

According to https://github.com/webpack/docs/wiki/hot-module-replacement-with-webpack

> If HMR is disabled all HMR code is removed by the compiler (wrap it in if(module.hot))

and everything of elm-hot-loader is wrapped in if(module.hot) :
https://github.com/fluxxu/elm-hot-loader/blob/master/hmr.js#L1

I think you should use different webpack config for development and production. Here is an example:
https://github.com/moarwick/elm-webpack-starter/blob/master/webpack.config.js#L81

Thanks!

**Comment by hulufei** [comment]
@fluxxu oh, I forgot that, thank you
