### ISSUE TITLE
Incompatible with elm-webpack-loader@3.0.1

### ISSUE THREAD

**Issue by bzf** [fluxxu/elm-hot-loader#14]
Hi,

I had an issue however using it with that latest version of https://github.com/rtfeldman/elm-webpack-loader (version 3.0.1). After failing a build (due to compiler error) it does not try to recompile the bundle on file updates.

You can reproduce it by installing the https://github.com/fluxxu/elm-hot-loader-starter project.

Thanks for the awesome stuff!

**Comment by fluxxu** [comment]
Hi,

I think this is related to:
https://github.com/rtfeldman/elm-webpack-loader/issues/53

I tried disable elm-hot-loader and the problem still persists.

**Comment by bzf** [comment]
@fluxxu Ah alright, yeah that makes sense. I also downgraded to 3.0.0 to get it working again.
