### ISSUE TITLE
Object.assign

### ISSUE THREAD

**Issue by kittykatattack** [fluxxu/elm-hot-loader#16]
Hi, 

`Object.assign` is not compatible with IE (all versions.)
Would you consider including an `Object.assign` pollyfill?

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by fluxxu** [comment]
Hi. Polyfill added
https://github.com/fluxxu/elm-hot-loader/blob/master/hmr.js#L6
and published as 0.3.4
Please test and let me know!
Thanks

**Comment by kittykatattack** [comment]
Thanks so much, this was much needed  👍
