### ISSUE TITLE
Initial command obliterates previous state

### ISSUE THREAD

**Issue by mattrrichard** [fluxxu/elm-hot-loader#18]
On start up, my app randomizes its state as part of its init command:

```
main =
    let 
        startupCmd = 
            Random.generate NewModel modelGenerator
    in
        Html.program
            { init = ( emptyModel, startupCmd )
            , update = update 
            , view = view
            , subscriptions = subscriptions
            }
```
  The problem here is that its `NewModel` message ticks _after_ the app's previous state is injected.  

Is this something that can be worked around by elm-hot-reload? If not, what about a way to signal to the app that it has been hot reloaded?  That way I could simply not issue the startup command in those cases.  e.g. :

```
main = 
    let
        startupCmd = 
            Random.generate NewModel modelGenerator

        init flags =
            if flags.hotSwapped then
                ( emptyModel, Cmd.none )
            else
                ( emptyModel, startupCmd )
    in
        Html.programWithFlags
            { init = init
            , update = update startupCmd discoCmd
            , view = view
            , subscriptions = subscriptions
            }
```

**Comment by fluxxu** [comment]
Hi,

I added this and published it to npm:
https://github.com/fluxxu/elm-hot-loader/blob/master/hmr.js#L164

Do you think this can solve your problem?

**Comment by mattrrichard** [comment]
I think something close to that would work, but  I don't believe that `__hotSwapped` is a valid record field name.

**Comment by fluxxu** [comment]
I think I came out a better way to solve your problem.
Now you can register callback to patch flags/state:
https://github.com/fluxxu/elm-hot-loader-starter/blob/master/src/index.js#L19
So you can

```
elm.hot.subscribe(function (event, context) {
  if (event === 'swap') {
    context.flags.hotSwapped = true
  }
})
```

Then your Main.init will get flags with hotSwapped  === true
**Please upgrade elm-hot-loader to 0.4.x to use this.**

**Comment by mattrrichard** [comment]
Finally got to test this, and yep it works well for me.  Thanks!
