### ISSUE TITLE
Document how to use the plugin with a compiled-to-js Elm app

### ISSUE THREAD

**Issue by Birowsky** [fluxxu/elm-hot-loader#19]
Since I'm using Webstorm, i leave it to it to compile the elm code. What I get as a result, obviously, is a js module that i'm including in my webpack config like so:

    resolve: {
      extensions: ['.js'],
      alias: {
        Elm: resolve('builds/intellij/scripts/elm-program.js')
      }
    }

Right now, a change in elm-program.js causes total reload.

**Comment by fluxxu** [comment]
If you don't use elm-webpack-loader to compile Elm, just make sure webpack uses elm-hot to load your compiled js file.
Add this to your webpack config file:

```
loaders: [
  // ...
  {
      test: /elm-program\.js$/,
      loader: 'elm-hot'
  }
  // ...
]
```

**Comment by Birowsky** [comment]
Yeah.. I already tried that. I still get full reload.

**Comment by Birowsky** [comment]
Fluxxu is super-friendly. Thanx to our chat we figured that because the compiled js is an "outside" module we need to pipe it through the elm-hot loader explicitly in the import statement:

`import {Main} from "elm-hot!Elm";`
