### ISSUE TITLE
Example does not run

### ISSUE THREAD

**Issue by simonh1000** [fluxxu/elm-hot-loader#2]
I think I followed the instructions completely, but ended up with this in my browser.
![image](https://cloud.githubusercontent.com/assets/5256724/13072077/983d8574-d497-11e5-8708-b7bb9e2086e7.png)

and this in the terminal console.  (I am using Ubuntu latest). It looks as though the elm code is not being compiled, but I know nothing about webpack so there is little I can do at present but post here

```
 webpack-dev-server --hot --inline --port 3000

http://localhost:3000/
webpack result is served from /
content is served from /home/sim/code/btsync/Elm/practise/hot-loading/example

ERROR in Cannot find module 'loader-utils'
 @ ./src/index.js 4:10-27
webpack: bundle is now VALID.
```

**Comment by fluxxu** [comment]
Hi! Did you run `npm install` in `/home/sim/code/btsync/Elm/practise/hot-loading/example`?
Looks line dependencies defined in `example/package.json` are not installed.

**Comment by simonh1000** [comment]
Hi, I have run npm install. One thing I can note is that this did not originally result in the installation of the loader-utils library, although even after doing that manually I still got the same errors

**Comment by fluxxu** [comment]
Oh! I can reproduce this problem now. Sorry, fixing it now...

**Comment by fluxxu** [comment]
Hi! Could you try it again?
You can either

Use your current clone, `npm install` in '/home/sim/code/btsync/Elm/practise/hot-loading' then `npm run dev` in the example folder

or

Update to the version I just pushed, `npm install` in '/home/sim/code/btsync/Elm/practise/hot-loading/example' then  `npm run dev` in the example folder

Thanks!

**Comment by simonh1000** [comment]
OK, I did `git pull origin` and followed your second instructions. It works!! 
Thanks. 
Will let you know what I make of it in due course :-)
