### ISSUE TITLE
Only works with programWithFlags ?

### ISSUE THREAD

**Issue by rundis** [fluxxu/elm-hot-loader#22]
It seems hot loading only retains state if you use programWithFlags ? (couldn't get it to keep state if using `Html.program`). 

If that's intentional (which is fine by me btw), maybe worth mentioning that limitation in the readme ?

tx again for a great tool :-)

**Comment by fluxxu** [comment]
Hi!
I just published 0.5.2 which should be fix this problem.
Thanks.
