### ISSUE TITLE
I see a weird error when not using Html.Events

### ISSUE THREAD

**Issue by ffigiel** [fluxxu/elm-hot-loader#23]
The error I see:
>  elm-hot-loader is incompatible with this version of Elm.

My environment:
 ```
$ npm ls --depth 0 | grep elm
├── elm@0.18.0
├── elm-hot-loader@0.5.2
├── elm-webpack-loader@3.0.6
```

Example code (App.elm)
```
module App exposing (..)

import Html exposing (..)


main =
    Html.program
        { init = initialState
        , update = update
        , subscriptions = (always Sub.none)
        , view = view
        }


type alias Model =
    Int


type Msg
    = X


initialState : ( Model, Cmd Msg )
initialState =
    ( 3, Cmd.none )


update : msg -> Model -> ( Model, Cmd Msg )
update msg model =
    ( model, Cmd.none )


view : Model -> Html Msg
view model =
    span [] [ text "Hello world!" ]
```

With this code, webpack will fail with the error message pasted above.

Now, if I add this line...
```
import Html.Events 
```
...the loader stops complaining and everything works.

**Comment by ffigiel** [comment]
Thanks, it's fixed now

**Comment by swsnr** [comment]
I have a similar issue.  Said error message appears for when as soon as I add `import List.Extra` to a module, with latest webpack, elm-loader and elm-hot-loader.
