### ISSUE TITLE
Changes not detected when elm-webpack "cache" option is enabled

### ISSUE THREAD

**Issue by opsb** [fluxxu/elm-hot-loader#24]
With the following config

```
    module: {
      loaders: [
        {
          test:    /\.elm$/,
          exclude: [/elm-stuff/, /node_modules/],
          loader:  'elm-hot!elm-webpack?cache=true&verbose=true&warn=false'
        },
```
changes are only detected in Main.elm. If I remove the cache option they're detected in any elm file. I don't know webpack well enough to know whether this is an inevitable consequence of enabling the cache option.

**Comment by fluxxu** [comment]
Hi,

All elm-hot do is to inject code to elm-webpack's result. If elm-webpack does not detect change, elm-hot does not get executed at all.

**Comment by opsb** [comment]
ok, sounds like I should open an issue on elm-webpack then.

**Comment by opsb** [comment]
opened https://github.com/rtfeldman/elm-webpack-loader/issues/75
