### ISSUE TITLE
Update elm-hot-loader to use latest elm-webpack-loader

### ISSUE THREAD

**Issue by halfzebra** [fluxxu/elm-hot-loader#25]
Currently, Elm Hot Loader has `elm-webpack-loader@^3.0.6` in peer dependencies.

[elm-webpack-loader](https://github.com/rtfeldman/elm-webpack-loader) was recently [updated](https://github.com/rtfeldman/elm-webpack-loader/releases/tag/4.0.0) to version `4.0.0`

It looks like hot reloading does not work with new version of the loader.

**Comment by sritchie** [comment]
So happy you just created this issue! I've been struggling today to get the reloader to work on any file other than `Main.elm`. Downgrading my webpack loader fixes hot reload.

**Comment by fluxxu** [comment]
I have no idea 😢 
I think it's a elm-webpack-loader bug...
I have submitted an issue there:
https://github.com/rtfeldman/elm-webpack-loader/issues/81

A patch is coming soon!
https://github.com/rtfeldman/elm-webpack-loader/pull/80

**Comment by slashdotdash** [comment]
@fluxxu the patch you mentioned has been merged into elm-webpack-loader ([#80](https://github.com/rtfeldman/elm-webpack-loader/pull/80)).

**Comment by halfzebra** [comment]
@slashdotdash, unfortunately, it fixes only the part of the problem.

**Comment by mblarsen** [comment]
I can see in the console that the new code is being fetched but no code is loaded.

**Comment by fluxxu** [comment]
Related to this:
https://github.com/rtfeldman/elm-webpack-loader/issues/85

Another patch is on the way:
https://github.com/rtfeldman/elm-webpack-loader/pull/86

No change is needed for elm-hot-loader.
I will update peerDependency after elm-webpack-loader release the fix. I guess the version number will be 4.1.1 ❔

**Comment by fluxxu** [comment]
elm-webpack-loader 4.1.1 released.
https://github.com/rtfeldman/elm-webpack-loader/issues/85#issuecomment-268596923
