### ISSUE TITLE
doesn't work on webpack-dev-server 2

### ISSUE THREAD

**Issue by arrizalamin** [fluxxu/elm-hot-loader#26]
I just upgraded webpack-dev-server to v2.3.0 and followed [webpack migration guide](https://webpack.js.org/guides/migrating/). HMR looks normal when code changes but all histories are gone and back to initial model.

**Comment by NicholasGWK** [comment]
Did you fix this? Trying with webpack 2 and I can't seem to get things to reload. Looks like it's triggering, but the page remains the same

**Comment by NicholasGWK** [comment]
Figured it out! I copied from a starter that was still using webpack 1, and upgraded to webpack 2 but didn't upgrade webpack-dev-server so I was still using 1.14...:D. Just commenting in case anyone else has a similar case of temporary stupidity :P

**Comment by opsb** [comment]
@NicholasGWK thank you! I did the exact same thing...
