### ISSUE TITLE
Feature: Flag to hot reload only after successful compile

### ISSUE THREAD

**Issue by tyleralves** [fluxxu/elm-hot-loader#27]
Feature Request:
Optional flag to have the hot loader only swap modules after the compiler compiles **successfully**. I also work with Typescript + Redux w/ HMR and it has always annoyed me when I make a small syntax mistake and HMR runs even though the compiler catches the error. At that point I have to navigate again to the proper view and replace state, as a result of a small error (or sometimes even a linting error)!

It would be great if I got a chance to look at the compiler error and make the quick change before elm-hot-loader kicks in.

Let me know if you need clarification.

PS: This package is amazing, thanks!!!

**Comment by fluxxu** [comment]
I don't think `elm-hot-loader` can help.
This loader just injects `hmr.js` to [elm-webpack-loader](https://github.com/elm-community/elm-webpack-loader/issues)'s result:
https://github.com/fluxxu/elm-hot-loader/blob/master/index.js#L32

I think you should open an issue in their repo:
https://github.com/elm-community/elm-webpack-loader/issues
