### ISSUE TITLE
Not triggering reload when I save any module other than Main

### ISSUE THREAD

**Issue by pixelprizm** [fluxxu/elm-hot-loader#29]
The issue: Main.elm imports MyComponent.elm.  When I save a change in MyComponent.elm, the page does not hot reload.  When I save a change in Main.elm, the page does reload.

Is this an error that's been encountered before?

Additional note: I'm using elm-css, and when I save a change to an elm css file (even if it's not the entry point), the CSS gets correctly reloaded.

File tree:
project root
* elm-package.json
* ...
* src
  * ...
  * elm
    * Main.elm
    * MyComponent.elm
  * index.js

My project is slightly customized (ejected) from the create-elm-app boilerplate
Index.js
```js
require('./elm/MainCss.elm');
var Elm = require('./elm/Main.elm');
var root = document.getElementById('root');
Elm.Main.embed(root);
```

My Webpack config (basically create-elm-app but with elm-css added in): https://gist.github.com/egauderman/c94cd24e9aedbcc0c2d0501121ec9645

Relevant NPM package versions:
```JSON
    "elm": "^0.18.0",
    "elm-css-webpack-loader": "^3.1.0",
    "elm-hot-loader": "0.5.4",
    "elm-webpack-loader": "4.3.0",
```
Relevant lines of elm-package.json:
```JSON
  "source-directories": [
    "src/elm"
  ],
  "exposed-modules": [],
  "dependencies": {
    "elm-lang/core": "5.0.0 <= v < 6.0.0",
    "elm-lang/html": "2.0.0 <= v < 3.0.0",
    "rtfeldman/elm-css": "8.2.0 <= v < 9.0.0",
    "rtfeldman/elm-css-helpers": "2.1.0 <= v < 3.0.0",
    "scottcorgan/elm-css-normalize": "1.1.7 <= v < 2.0.0"
  },
  "elm-version": "0.18.0 <= v < 0.19.0"
```

**Comment by fluxxu** [comment]
Hi,

I tried to reproduce this issue here:
https://github.com/fluxxu/elm-hot-loader-issue-29
But HMR works on my side...
Could you try to break it so I can debug the issue?

**Comment by joanllenas** [comment]
Exact same problem.
I was using create-elm-app v0.4.0 but there have been a [few releases](https://github.com/halfzebra/create-elm-app/releases) lately that fix this issue.

**Comment by mattraykowski** [comment]
I ran into this problem as well. I realized that it wasn't only not reloading but it was also not recompiling. It took a little digging but it appears that you need to do this:

`{ loader: 'elm-webpack-loader', options: { /* your normal options and then */ cwd: '/path/to/source' }`

https://github.com/elm-community/elm-webpack-loader#cwd-default-null-recommended

Adding `cwd: './'` to my loader options fixed the problem.

**Comment by pixelprizm** [comment]
@mattraykowski  Ah yeah you're right, it's actually not even recompiling.  However the `cwd` option didn't seem to fix my issue; saving the child component still doesn't trigger recompile.

@joanllenas  I was using create-elm-app v0.4.0 as well, so I'll try upgrading and remaking my boilerplate.

**Comment by pixelprizm** [comment]
@joanllenas that worked for me.  I looked at the new config generated by create-elm-app v0.6.0 and copied some new things over.

It seems that the fix is to add `forceWatch: true` to the elm-webpack-loader options:

```js
      {
        test: /\.elm$/,
        exclude: [ /elm-stuff/, /node_modules/, /MainCss\.elm/ ],
        use: [
          {
            loader: 'elm-hot-loader'
          },
          {
            loader: 'elm-webpack-loader',
            options: {
              verbose: true,
              warn: true,
              debug: true,
              pathToMake: paths.elmMake,
              forceWatch: true
            }
          }
        ]
      },
```

**Comment by pixelprizm** [comment]
Thanks for your help everyone!
