### ISSUE TITLE
Compiler errors in the browser

### ISSUE THREAD

**Issue by boxed** [fluxxu/elm-hot-loader#32]
This project looks very cool, but it's a pity compiler errors don't show up in the browser. Figwheel for ClojureScript does this and it's very nice :P

**Comment by fluxxu** [comment]
Hi, thanks for your interest in this project.
This project is just an ugly patch to the output of elm-make to implement [Webpack's HMR](https://webpack.js.org/concepts/hot-module-replacement/) interface.
The actual change detect/compile work is done by [elm-webpack-loader](https://github.com/elm-community/elm-webpack-loader).

Please use [create-elm-app](https://github.com/halfzebra/create-elm-app) to get a nice error overlay in browser :)

![image](https://user-images.githubusercontent.com/4956828/27242106-98d2d692-52a9-11e7-939d-5b22d1d83645.png)
