### ISSUE TITLE
Help integrating into elm-webpack-starter?

### ISSUE THREAD

**Issue by moarwick** [fluxxu/elm-hot-loader#6]
Hello. I'm the author of [elm-webpack-starter](https://github.com/moarwick/elm-webpack-starter), and I've now received several requests to integrate your hot-loader into it (on GitHub and the Elm Google group). Ironically, even though it's my most popular repo, I'm not very familiar with Elm -- I've only tried it over a weekend, which is when I created the build setup. Any interest doing a PR, so it's done correctly? Specifically, the port/swap/Signal shenanigans.. Thanks!

**Comment by gothy** [comment]
+1 Yes, please! :)

p.s. I might be doing this PR in a week or two if nobody volunteers. I think this is a must-have project for the Elm community to ease the path for beginners.

**Comment by fluxxu** [comment]
https://github.com/moarwick/elm-webpack-starter/pull/9

Done. :)
