### ISSUE TITLE
0.17 support

### ISSUE THREAD

**Issue by fluxxu** [fluxxu/elm-hot-loader#9]
- [x] Research: Inject code
- [x] Research: Watch/save state change
- [x] Research: Swap elm instance without using port/subscription
- [x] Research: Remove all event listeners added by the previous instance
- [x] Implenment & Test

**Comment by Fresheyeball** [comment]
:+1:

**Comment by glenjamin** [comment]
I had a little look into this today, but the `Elm` object no longer has `swap` or `dispose`, so It seems like this will be quite difficult without reaching deeper into the internals, or doing something even wackier.

**Comment by fluxxu** [comment]
I just published 0.3.0:
Elm 0.17 support
swap port and EmptyAction are gone. Enable this loader and it just works.
Incoming ports still work after hot swapping

@glenjamin Yes, I had to read source code again and again to find a wacky way to implement this. 😄

**Comment by Fresheyeball** [comment]
:100: @fluxxu rock on
